### ISSUE TITLE
Current or recommended version is not displayed as defaultValue

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/mui-tests#1]
## Issue

Current or recommended version is not selected as value within the pop-up list

![Screenshot 2024-03-13 at 17 46 49](https://github.com/ch007m/mui-tests/assets/463790/b14c4df5-13e1-47f0-94cb-500f22b46ff5)

Code: https://github.com/ch007m/mui-tests/blob/main/src/Version.tsx#L71

**Comment by cmoulliard** [comment]
If we try to use `defaultValue` or `inputValue` 
```
        <Autocomplete
            id="quarkus-versions"
            options={quarkusVersion}
            getOptionLabel={(quarkusVersion) => quarkusVersion.id}
            defaultValue={recommendedVersion}
            sx={{ width: 300, marginTop: 6, marginX: "auto" }}
            renderInput={(params) => (
                <TextField
                    {...params}
                    label="Select a quarkus version"
                    size="small"
                />
            )}
        />
```
then we got such error 
<img width="1626" alt="Screenshot 2024-03-14 at 09 26 17" src="https://github.com/ch007m/mui-tests/assets/463790/601face3-85ea-4d93-89d4-f38b384538ac">

**Comment by iocanel** [comment]
My guess, is that the component is initially rendered with no values / selected value (are not yet available) and then the values are set, which is not well handed by the component. I would try to only render the component when the available versions have been loaded.

**Comment by cmoulliard** [comment]
I found how to fix it. Still one point to be fixed 

```
        <Autocomplete
            id="quarkus-versions"
            options={quarkusVersion}
            getOptionLabel={(quarkusVersion) => quarkusVersion.id}
            defaultValue={{id: "3.8", lts: false}} <== How the default value should be declared instead of a string version !
            sx={{ width: 300, marginTop: 6, marginX: "auto" }}
            renderInput={(params) => (
                <TextField
                    {...params}
                    label="Select a quarkus version"
                    size="small"
                />
            )}
        />
```
=>
![Screenshot 2024-03-14 at 09 50 27](https://github.com/ch007m/mui-tests/assets/463790/3648c902-b50a-41c7-891d-a6153f7b427a)

**Comment by cmoulliard** [comment]
> I would try to only render the component when the available versions have been loaded.

How ?

**Comment by cmoulliard** [comment]
Do you know why that works using `defaultValue={{id: "3.8", lts: false}}` and not the object `Version` or Array Version [here](https://github.com/ch007m/mui-tests/blob/08e6f7827ee3ee1a76fd4b3fb9983a22a98cbb93/src/Version.tsx#L83-L85) ? @iocanel 
```
    useEffect(() => {
        if (quarkusVersion && recommendedVersion) {
            if (Array.isArray(quarkusVersion)) {
                displayVersions(quarkusVersion);
                quarkusVersion.forEach((v, idx) => {
                    if (v.id === recommendedVersion) {
                        console.log("Version matches the recommended: " + v.id + ", " + v.lts)
                        setDefaultVersion(quarkusVersion[idx])
                    } else {
                        console.log("No version matching the recommended: " + recommendedVersion + ", against: " + v.id)
                    }
                })
            }
        }
    }, [quarkusVersion]);

    return (
        <Autocomplete
            id="quarkus-versions"
            isOptionEqualToValue={(option, value) => option.id === value.id}
            options={quarkusVersion}
            getOptionLabel={(quarkusVersion) => quarkusVersion.id}
            // That don't work using Version array or Version object => {defaultVersion}
            // BUT that works using => {{id: "3.8", lts: false}}
            defaultValue={{id: "3.8", lts: false}}
```
According to MUI [doc](https://mui.com/material-ui/api/autocomplete/), the defaultValue is of type `any` and its default is `props.multiple ? [] : null`. It is used when `Use when the component is not controlled.`

**Comment by cmoulliard** [comment]
Issue fixed: https://github.com/ch007m/mui-tests/blob/main/src/Version.tsx#L22 @iocanel
